name: Selenium TestNG (14:00 Europe/Belgrade)

on:
  schedule:
    # Summer time (CEST, UTC+2) → run at 12:00 UTC
    - cron: '0 12 * 4-10 *'
    # Winter time (CET, UTC+1) → run at 13:00 UTC
    - cron: '0 13 * 1-3,11-12 *'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run TestNG suite
        run: mvn clean test

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**